<a href="https://colab.research.google.com/github/kvssri/online-tihiitg/blob/main/Final%20Technical%20Review.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# ==========================================
# FINAL TECHNICAL REVIEW
# ==========================================

import pandas as pd
import numpy as np
import os
import json

print("Final Technical Review")
print("======================")
print("Notebook started successfully.")

Final Technical Review
======================
Notebook started successfully.

In [2]:
# ==========================================
# STEP 2: FINAL METHOD
# ==========================================

final_method = {
    "Project": "Underwater Image Enhancement using GAN",
    "Model": "Tuned TCN",
    "Configuration": "TCN-4",
    "Hidden Channels": 64,
    "Dropout": 0.0,
    "Learning Rate": 0.0005,
    "Batch Size": 32,
    "Epochs": 15,
    "Sequence Length": 10,
    "Features": ["epoch", "step", "disc_loss", "time_s"],
    "Target": "gen_total",
    "Data Split": "70% Train / 15% Validation / 15% Test",
    "Normalization": "StandardScaler fitted only on training data",
    "Loss Function": "MSELoss",
    "Optimizer": "Adam"
}

print("FINAL METHOD")
print("============")

for key, value in final_method.items():
    print(f"{key}: {value}")

FINAL METHOD
============
Project: Underwater Image Enhancement using GAN
Model: Tuned TCN
Configuration: TCN-4
Hidden Channels: 64
Dropout: 0.0
Learning Rate: 0.0005
Batch Size: 32
Epochs: 15
Sequence Length: 10
Features: ['epoch', 'step', 'disc_loss', 'time_s']
Target: gen_total
Data Split: 70% Train / 15% Validation / 15% Test
Normalization: StandardScaler fitted only on training data
Loss Function: MSELoss
Optimizer: Adam

In [3]:
from google.colab import files

uploaded = files.upload()

print("Uploaded file(s):")
for filename in uploaded.keys():
    print(filename)

Saving Underwater-Image-Data-set-main.zip to Underwater-Image-Data-set-main.zip
Uploaded file(s):
Underwater-Image-Data-set-main.zip

In [6]:
# ==========================================
# STEP 5: UPLOAD AND EXTRACT ZIP
# ==========================================

from google.colab import files
import zipfile
import os

uploaded = files.upload()

zip_file = list(uploaded.keys())[0]

extract_folder = "/content/final_review_data"
os.makedirs(extract_folder, exist_ok=True)

with zipfile.ZipFile(zip_file, "r") as zip_ref:
    zip_ref.extractall(extract_folder)

print("ZIP uploaded successfully.")
print("ZIP file:", zip_file)
print("Data extracted to:", extract_folder)

Saving Underwater-Image-Data-set-main.zip to Underwater-Image-Data-set-main (1).zip
ZIP uploaded successfully.
ZIP file: Underwater-Image-Data-set-main (1).zip
Data extracted to: /content/final_review_data

In [7]:
# ==========================================
# STEP 6: FIND TRAINING LOG CSV FILES
# ==========================================

import glob
import os

csv_files = glob.glob(
    "/content/final_review_data/**/*.csv",
    recursive=True
)

print("CSV files found:", len(csv_files))
print("\nFiles:")

for f in csv_files:
    print("-", f)

CSV files found: 8

Files:
- /content/final_review_data/Underwater-Image-Data-set-main/training_log 2.csv
- /content/final_review_data/Underwater-Image-Data-set-main/training_log 4.csv
- /content/final_review_data/Underwater-Image-Data-set-main/training_log 6.csv
- /content/final_review_data/Underwater-Image-Data-set-main/training_log 8.csv
- /content/final_review_data/Underwater-Image-Data-set-main/training_log 1.csv
- /content/final_review_data/Underwater-Image-Data-set-main/training_log 5.csv
- /content/final_review_data/Underwater-Image-Data-set-main/training_log 7.csv
- /content/final_review_data/Underwater-Image-Data-set-main/training_log 3.csv

In [8]:
# ==========================================
# STEP 7: COMBINE TRAINING LOGS
# ==========================================

import pandas as pd
import os

all_logs = []

for file in csv_files:
    df_temp = pd.read_csv(file)
    df_temp["source_file"] = os.path.basename(file)
    all_logs.append(df_temp)

combined_df = pd.concat(all_logs, ignore_index=True)

print("Combined dataset shape:", combined_df.shape)
print("\nColumns:")
print(combined_df.columns.tolist())

print("\nFirst 5 rows:")
display(combined_df.head())

Combined dataset shape: (24915, 6)

Columns:
['epoch', 'step', 'gen_total', 'disc_loss', 'time_s', 'source_file']

First 5 rows:

   epoch  step  gen_total  disc_loss      time_s         source_file
0      1    30  39.782654   0.618856  130.054897  training_log 2.csv
1      1    31  39.431751   0.594878  135.857588  training_log 2.csv
2      1    32  31.144588   0.691624  140.604372  training_log 2.csv
3      1    33  57.094162   0.559530  145.975339  training_log 2.csv
4      1    34  46.443527   0.533368  149.309059  training_log 2.csv

In [9]:
# ==========================================
# STEP 8: FINAL MODEL SETTINGS
# ==========================================

FEATURES = ["epoch", "step", "disc_loss", "time_s"]
TARGET = "gen_total"

SEQUENCE_LENGTH = 10

TRAIN_RATIO = 0.70
VALIDATION_RATIO = 0.15
TEST_RATIO = 0.15

HIDDEN_CHANNELS = 64
DROPOUT = 0.0
LEARNING_RATE = 0.0005
BATCH_SIZE = 32
EPOCHS = 15

RANDOM_SEED = 42

print("FINAL MODEL SETTINGS")
print("====================")

print("Features:", FEATURES)
print("Target:", TARGET)
print("Sequence length:", SEQUENCE_LENGTH)
print("Split:", "70% Train / 15% Validation / 15% Test")
print("Hidden channels:", HIDDEN_CHANNELS)
print("Dropout:", DROPOUT)
print("Learning rate:", LEARNING_RATE)
print("Batch size:", BATCH_SIZE)
print("Epochs:", EPOCHS)

FINAL MODEL SETTINGS
====================
Features: ['epoch', 'step', 'disc_loss', 'time_s']
Target: gen_total
Sequence length: 10
Split: 70% Train / 15% Validation / 15% Test
Hidden channels: 64
Dropout: 0.0
Learning rate: 0.0005
Batch size: 32
Epochs: 15

In [10]:
# ==========================================
# STEP 9: CREATE SEQUENCES
# ==========================================

X_data = combined_df[FEATURES].values
y_data = combined_df[TARGET].values

X_sequences = []
y_sequences = []

for i in range(len(X_data) - SEQUENCE_LENGTH):
    X_sequences.append(
        X_data[i:i + SEQUENCE_LENGTH]
    )
    y_sequences.append(
        y_data[i + SEQUENCE_LENGTH]
    )

X_sequences = np.array(X_sequences)
y_sequences = np.array(y_sequences)

print("Sequences created successfully.")
print("X shape:", X_sequences.shape)
print("y shape:", y_sequences.shape)

Sequences created successfully.
X shape: (24905, 10, 4)
y shape: (24905,)

In [11]:
# ==========================================
# STEP 10: TIME-ORDERED DATA SPLIT
# ==========================================

total_samples = len(X_sequences)

train_end = int(total_samples * TRAIN_RATIO)
validation_end = int(
    total_samples * (TRAIN_RATIO + VALIDATION_RATIO)
)

X_train = X_sequences[:train_end]
y_train = y_sequences[:train_end]

X_val = X_sequences[train_end:validation_end]
y_val = y_sequences[train_end:validation_end]

X_test = X_sequences[validation_end:]
y_test = y_sequences[validation_end:]

print("TIME-ORDERED SPLIT")
print("==================")
print("Training samples:", len(X_train))
print("Validation samples:", len(X_val))
print("Test samples:", len(X_test))

print("\nSplit percentages:")
print("Train:", len(X_train) / total_samples * 100, "%")
print("Validation:", len(X_val) / total_samples * 100, "%")
print("Test:", len(X_test) / total_samples * 100, "%")

TIME-ORDERED SPLIT
==================
Training samples: 17433
Validation samples: 3736
Test samples: 3736

Split percentages:
Train: 69.99799237100984 %
Validation: 15.001003814495082 %
Test: 15.001003814495082 %

In [12]:
# ==========================================
# STEP 11: TRAINING-ONLY NORMALIZATION
# ==========================================

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# Reshape training data for fitting
train_2d = X_train.reshape(-1, X_train.shape[-1])

# Fit ONLY on training data
scaler.fit(train_2d)

# Apply the same scaler to all sets
X_train_scaled = scaler.transform(
    X_train.reshape(-1, X_train.shape[-1])
).reshape(X_train.shape)

X_val_scaled = scaler.transform(
    X_val.reshape(-1, X_val.shape[-1])
).reshape(X_val.shape)

X_test_scaled = scaler.transform(
    X_test.reshape(-1, X_test.shape[-1])
).reshape(X_test.shape)

print("Normalization completed successfully.")
print("Scaler fitted only on training data.")

print("\nScaled shapes:")
print("X_train:", X_train_scaled.shape)
print("X_val:", X_val_scaled.shape)
print("X_test:", X_test_scaled.shape)

Normalization completed successfully.
Scaler fitted only on training data.

Scaled shapes:
X_train: (17433, 10, 4)
X_val: (3736, 10, 4)
X_test: (3736, 10, 4)

In [13]:
# ==========================================
# STEP 12: FINAL TCN MODEL
# ==========================================

import torch
import torch.nn as nn

class TCNModel(nn.Module):
    def __init__(self, input_size):
        super().__init__()

        self.network = nn.Sequential(
            nn.Conv1d(
                input_size, 64,
                kernel_size=3,
                padding=1
            ),
            nn.ReLU(),

            nn.Conv1d(
                64, 64,
                kernel_size=3,
                padding=2,
                dilation=2
            ),
            nn.ReLU(),

            nn.Conv1d(
                64, 32,
                kernel_size=3,
                padding=4,
                dilation=4
            ),
            nn.ReLU()
        )

        self.fc = nn.Linear(32, 1)

    def forward(self, x):
        x = x.transpose(1, 2)
        x = self.network(x)
        x = x[:, :, -1]
        return self.fc(x)


# Create model
input_size = len(FEATURES)

model = TCNModel(input_size)

print("Final TCN model created successfully.")
print(model)

Final TCN model created successfully.
TCNModel(
  (network): Sequential(
    (0): Conv1d(4, 64, kernel_size=(3,), stride=(1,), padding=(1,))
    (1): ReLU()
    (2): Conv1d(64, 64, kernel_size=(3,), stride=(1,), padding=(2,), dilation=(2,))
    (3): ReLU()
    (4): Conv1d(64, 32, kernel_size=(3,), stride=(1,), padding=(4,), dilation=(4,))
    (5): ReLU()
  )
  (fc): Linear(in_features=32, out_features=1, bias=True)
)

In [14]:
# ==========================================
# STEP 13: TRAIN FINAL TCN
# ==========================================

from torch.utils.data import TensorDataset, DataLoader

torch.manual_seed(RANDOM_SEED)
np.random.seed(RANDOM_SEED)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

X_train_tensor = torch.tensor(X_train_scaled, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.float32).view(-1, 1)

X_val_tensor = torch.tensor(X_val_scaled, dtype=torch.float32)
y_val_tensor = torch.tensor(y_val, dtype=torch.float32).view(-1, 1)

train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
val_dataset = TensorDataset(X_val_tensor, y_val_tensor)

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False
)

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False
)

model = TCNModel(len(FEATURES)).to(device)

criterion = nn.MSELoss()

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=LEARNING_RATE
)

best_val_loss = float("inf")
best_model_state = None

train_history = []
val_history = []

print("Training final TCN...")
print("Device:", device)

for epoch in range(EPOCHS):

    model.train()
    train_loss = 0.0

    for X_batch, y_batch in train_loader:

        X_batch = X_batch.to(device)
        y_batch = y_batch.to(device)

        optimizer.zero_grad()

        predictions = model(X_batch)

        loss = criterion(predictions, y_batch)

        loss.backward()
        optimizer.step()

        train_loss += loss.item() * len(X_batch)

    train_loss /= len(train_dataset)

    # Validation
    model.eval()
    val_loss = 0.0

    with torch.no_grad():
        for X_batch, y_batch in val_loader:

            X_batch = X_batch.to(device)
            y_batch = y_batch.to(device)

            predictions = model(X_batch)

            loss = criterion(predictions, y_batch)

            val_loss += loss.item() * len(X_batch)

    val_loss /= len(val_dataset)

    train_history.append(train_loss)
    val_history.append(val_loss)

    if val_loss < best_val_loss:
        best_val_loss = val_loss
        best_model_state = model.state_dict()

    print(
        f"Epoch {epoch+1:02d}/{EPOCHS} | "
        f"Train Loss: {train_loss:.6f} | "
        f"Val Loss: {val_loss:.6f}"
    )

# Restore best validation model
model.load_state_dict(best_model_state)

print("\nFinal TCN training completed.")
print("Best validation loss:", best_val_loss)

Training final TCN...
Device: cpu
Epoch 01/15 | Train Loss: 108.261068 | Val Loss: 64.762450
Epoch 02/15 | Train Loss: 37.719317 | Val Loss: 54.811555
Epoch 03/15 | Train Loss: 34.863273 | Val Loss: 50.143147
Epoch 04/15 | Train Loss: 33.484216 | Val Loss: 47.608835
Epoch 05/15 | Train Loss: 32.308475 | Val Loss: 46.427215
Epoch 06/15 | Train Loss: 31.635104 | Val Loss: 45.535642
Epoch 07/15 | Train Loss: 31.017225 | Val Loss: 44.307914
Epoch 08/15 | Train Loss: 30.663433 | Val Loss: 44.414390
Epoch 09/15 | Train Loss: 30.543711 | Val Loss: 43.990832
Epoch 10/15 | Train Loss: 30.234098 | Val Loss: 43.827132
Epoch 11/15 | Train Loss: 30.022545 | Val Loss: 43.713758
Epoch 12/15 | Train Loss: 29.797901 | Val Loss: 43.546292
Epoch 13/15 | Train Loss: 29.851989 | Val Loss: 43.909796
Epoch 14/15 | Train Loss: 29.922578 | Val Loss: 44.966079
Epoch 15/15 | Train Loss: 29.981469 | Val Loss: 45.472109

Final TCN training completed.
Best validation loss: 43.5462921314117

In [15]:
# ==========================================
# STEP 14: FINAL TEST METRICS
# ==========================================

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

model.eval()

X_test_tensor = torch.tensor(
    X_test_scaled,
    dtype=torch.float32
).to(device)

with torch.no_grad():
    predictions = model(X_test_tensor)

y_pred = predictions.cpu().numpy().flatten()
y_actual = y_test.flatten()

# Metrics
mae = mean_absolute_error(y_actual, y_pred)

rmse = np.sqrt(
    mean_squared_error(y_actual, y_pred)
)

# Avoid division by zero in MAPE
non_zero = y_actual != 0

mape = np.mean(
    np.abs(
        (y_actual[non_zero] - y_pred[non_zero])
        / y_actual[non_zero]
    )
) * 100

r2 = r2_score(y_actual, y_pred)

print("FINAL TEST RESULTS")
print("==================")
print(f"MAE  : {mae:.6f}")
print(f"RMSE : {rmse:.6f}")
print(f"MAPE : {mape:.6f}%")
print(f"R²   : {r2:.6f}")

FINAL TEST RESULTS
==================
MAE  : 2.412714
RMSE : 3.164585
MAPE : 18.652487%
R²   : 0.132594

In [16]:
# ==========================================
# STEP 15: SAVE FINAL METRICS
# ==========================================

final_results = pd.DataFrame({
    "Metric": ["MAE", "RMSE", "MAPE", "R2"],
    "Value": [mae, rmse, mape, r2]
})

final_results.to_csv(
    "/content/final_review_metrics.csv",
    index=False
)

print("Final metrics saved successfully.")
display(final_results.round(6))

Final metrics saved successfully.

  Metric      Value
0    MAE   2.412714
1   RMSE   3.164585
2   MAPE  18.652487
3     R2   0.132594

In [17]:
# ==========================================
# STEP 16: REPRODUCIBLE WORKFLOW
# ==========================================

workflow = [
    "1. Input: GAN training logs from the ZIP file",
    "2. Extract and combine the 8 training-log CSV files",
    "3. Check and order the records by training progression",
    "4. Select features: epoch, step, disc_loss, time_s",
    "5. Select target: gen_total",
    "6. Create sequences of 10 consecutive time steps",
    "7. Split data into 70% train, 15% validation and 15% test",
    "8. Fit StandardScaler using training data only",
    "9. Apply the trained scaler to validation and test data",
    "10. Feed sequences into the Tuned TCN (TCN-4)",
    "11. Generate gen_total predictions",
    "12. Evaluate on the held-out test set",
    "13. Report MAE, RMSE, MAPE and R²",
    "14. Perform final error analysis and documentation"
]

print("REPRODUCIBLE INPUT-TO-OUTPUT WORKFLOW")
print("=====================================")

for step in workflow:
    print(step)

REPRODUCIBLE INPUT-TO-OUTPUT WORKFLOW
=====================================
1. Input: GAN training logs from the ZIP file
2. Extract and combine the 8 training-log CSV files
3. Check and order the records by training progression
4. Select features: epoch, step, disc_loss, time_s
5. Select target: gen_total
6. Create sequences of 10 consecutive time steps
7. Split data into 70% train, 15% validation and 15% test
8. Fit StandardScaler using training data only
9. Apply the trained scaler to validation and test data
10. Feed sequences into the Tuned TCN (TCN-4)
11. Generate gen_total predictions
12. Evaluate on the held-out test set
13. Report MAE, RMSE, MAPE and R²
14. Perform final error analysis and documentation

In [18]:
# ==========================================
# STEP 17: FINAL ERROR-ANALYSIS REQUIREMENTS
# ==========================================

error_analysis_requirements = [
    "1. Report MAE, RMSE, MAPE and R² on the held-out test set.",
    "2. Compare actual vs predicted gen_total values.",
    "3. Identify the samples with the largest absolute prediction errors.",
    "4. Calculate the 95th percentile absolute error.",
    "5. Inspect unusual or high-error cases.",
    "6. Check whether errors are concentrated in particular source files or training conditions.",
    "7. Save the final predictions for reproducibility.",
    "8. Clearly document limitations and remaining questions."
]

print("FINAL ERROR-ANALYSIS REQUIREMENTS")
print("=================================")

for item in error_analysis_requirements:
    print(item)

FINAL ERROR-ANALYSIS REQUIREMENTS
=================================
1. Report MAE, RMSE, MAPE and R² on the held-out test set.
2. Compare actual vs predicted gen_total values.
3. Identify the samples with the largest absolute prediction errors.
4. Calculate the 95th percentile absolute error.
5. Inspect unusual or high-error cases.
6. Check whether errors are concentrated in particular source files or training conditions.
7. Save the final predictions for reproducibility.
8. Clearly document limitations and remaining questions.

In [19]:
# ==========================================
# STEP 18: REMAINING QUESTIONS & CORRECTIONS
# ==========================================

remaining_questions = [
    "1. Are the source files independent GAN training runs or do they represent physical units?",
    "2. Are verified temporal or degradation-stage labels available?",
    "3. Can the final model be tested on completely unseen training runs?",
    "4. Are image-level enhancement metrics such as PSNR, SSIM, UIQM or UCIQE available?",
    "5. Does the mentor require any additional validation or reporting?",
]

correction_list = [
    "1. Use source_file as a training-run/source identifier, not as a cell ID.",
    "2. Do not describe gen_total as SoH or RUL.",
    "3. Do not describe target-derived groups as verified degradation stages.",
    "4. Preserve the training-only StandardScaler to avoid data leakage.",
    "5. Preserve the held-out test set for final evaluation.",
    "6. Avoid sequences crossing source-file boundaries in a future cleaned revision.",
    "7. Record actual mentor corrections after the final review; mentor approval is currently pending."
]

print("REMAINING QUESTIONS")
print("===================")

for item in remaining_questions:
    print(item)

print("\nCORRECTION LIST")
print("===============")

for item in correction_list:
    print(item)

REMAINING QUESTIONS
===================
1. Are the source files independent GAN training runs or do they represent physical units?
2. Are verified temporal or degradation-stage labels available?
3. Can the final model be tested on completely unseen training runs?
4. Are image-level enhancement metrics such as PSNR, SSIM, UIQM or UCIQE available?
5. Does the mentor require any additional validation or reporting?

CORRECTION LIST
===============
1. Use source_file as a training-run/source identifier, not as a cell ID.
2. Do not describe gen_total as SoH or RUL.
3. Do not describe target-derived groups as verified degradation stages.
4. Preserve the training-only StandardScaler to avoid data leakage.
5. Preserve the held-out test set for final evaluation.
6. Avoid sequences crossing source-file boundaries in a future cleaned revision.
7. Record actual mentor corrections after the final review; mentor approval is currently pending.

In [20]:
# ==========================================
# STEP 19: FINAL TECHNICAL REVIEW SUMMARY
# ==========================================

final_review = {
    "Final Method": "Tuned TCN (TCN-4)",
    "Input": "GAN training logs from 8 runs",
    "Features": "epoch, step, disc_loss, time_s",
    "Target": "gen_total",
    "Sequence Length": 10,
    "Data Split": "70% Train / 15% Validation / 15% Test",
    "Normalization": "Training-only StandardScaler",
    "Model": "TCN with 64 hidden channels and 0.0 dropout",
    "Learning Rate": 0.0005,
    "Batch Size": 32,
    "Training Epochs": 15,
    "Optimizer": "Adam",
    "Loss": "MSELoss",
    "Validation": "Held-out test evaluation using MAE, RMSE, MAPE and R²",
    "Error Analysis": "Actual vs predicted values, largest errors, 95th percentile error and source/condition analysis",
    "Mentor Status": "Final mentor confirmation pending"
}

print("FINAL TECHNICAL REVIEW")
print("======================")

for key, value in final_review.items():
    print(f"{key}: {value}")

FINAL TECHNICAL REVIEW
======================
Final Method: Tuned TCN (TCN-4)
Input: GAN training logs from 8 runs
Features: epoch, step, disc_loss, time_s
Target: gen_total
Sequence Length: 10
Data Split: 70% Train / 15% Validation / 15% Test
Normalization: Training-only StandardScaler
Model: TCN with 64 hidden channels and 0.0 dropout
Learning Rate: 0.0005
Batch Size: 32
Training Epochs: 15
Optimizer: Adam
Loss: MSELoss
Validation: Held-out test evaluation using MAE, RMSE, MAPE and R²
Error Analysis: Actual vs predicted values, largest errors, 95th percentile error and source/condition analysis
Mentor Status: Final mentor confirmation pending

In [21]:
# ==========================================
# STEP 20: CREATE 3-SLIDE PROGRESS PACK
# ==========================================

!pip -q install python-pptx

from pptx import Presentation
from pptx.util import Inches, Pt

prs = Presentation()

# ---------- Helper ----------
def add_title(slide, title):
    title_box = slide.shapes.add_textbox(
        Inches(0.5), Inches(0.3), Inches(12), Inches(0.7)
    )
    p = title_box.text_frame.paragraphs[0]
    p.text = title
    p.font.size = Pt(26)
    p.font.bold = True

def add_bullets(slide, items, x=0.7, y=1.2, w=11.8, h=5.8):
    box = slide.shapes.add_textbox(
        Inches(x), Inches(y), Inches(w), Inches(h)
    )
    tf = box.text_frame
    tf.word_wrap = True

    for i, item in enumerate(items):
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        p.text = item
        p.font.size = Pt(17)
        p.space_after = Pt(10)

# ==================================================
# SLIDE 1 — FINAL METHOD & WORKFLOW
# ==================================================

slide = prs.slides.add_slide(prs.slide_layouts[6])

add_title(
    slide,
    "Final Method & Reproducible Input-to-Output Workflow"
)

slide1_items = [
    "Input: GAN training logs from 8 runs",
    "Features: epoch, step, disc_loss, time_s",
    "Target: gen_total",
    "Sequence length: 10 time steps",
    "Split: 70% train / 15% validation / 15% test",
    "Normalization: StandardScaler fitted only on training data",
    "Final model: Tuned TCN (TCN-4) — 64 hidden channels, 0.0 dropout",
    "Learning rate: 0.0005 | Batch size: 32 | Epochs: 15",
    "Workflow: Logs → preprocessing → sequences → scaling → TCN → prediction → test evaluation → error analysis"
]

add_bullets(slide, slide1_items)

# ==================================================
# SLIDE 2 — VALIDATION RESULTS
# ==================================================

slide = prs.slides.add_slide(prs.slide_layouts[6])

add_title(
    slide,
    "Final Validation Results & Model Selection"
)

# Read actual values from the metrics table
metric_values = final_results.set_index("Metric")["Value"]

slide2_items = [
    f"MAE: {metric_values['MAE']:.6f}",
    f"RMSE: {metric_values['RMSE']:.6f}",
    f"MAPE: {metric_values['MAPE']:.6f}%",
    f"R²: {metric_values['R2']:.6f}",
    "Selected model: Tuned TCN (TCN-4)",
    "TCN-4 validation evidence: best Day-19 validation loss = 22.040364",
    "Final evaluation uses the held-out test set.",
    "Model complexity: 19,393 trainable parameters",
    "Performance should be interpreted together with model complexity and the dataset limitations."
]

add_bullets(slide, slide2_items)

# ==================================================
# SLIDE 3 — ERROR ANALYSIS & CORRECTIONS
# ==================================================

slide = prs.slides.add_slide(prs.slide_layouts[6])

add_title(
    slide,
    "Error Analysis, Remaining Questions & Correction List"
)

slide3_items = [
    "Error analysis: report MAE, RMSE, MAPE and R².",
    "Inspect actual vs predicted values and identify the largest errors.",
    "Report the 95th percentile absolute error and investigate unusual cases.",
    "Check whether errors are concentrated in particular source files or conditions.",
    "Remaining question: are source files independent GAN runs or physical units?",
    "Remaining question: are verified temporal/degradation-stage labels available?",
    "Correction: source_file should be described as a training-run/source identifier, not a cell ID.",
    "Correction: gen_total must not be described as SoH/RUL.",
    "Correction: target-derived groups must not be called verified degradation stages.",
    "Correction: future cleaned revision should prevent sequences crossing source-file boundaries.",
    "Mentor corrections/approval: pending final mentor confirmation."
]

add_bullets(slide, slide3_items)

# ---------- Save ----------
ppt_path = "/content/Final_Technical_Review_3_Slide_Progress_Pack.pptx"
prs.save(ppt_path)

print("3-slide progress pack created successfully!")
print("Saved at:", ppt_path)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 472.8/472.8 kB 2.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.3/175.3 kB 10.0 MB/s eta 0:00:00
3-slide progress pack created successfully!
Saved at: /content/Final_Technical_Review_3_Slide_Progress_Pack.pptx

In [22]:
from google.colab import files

files.download(
    "/content/Final_Technical_Review_3_Slide_Progress_Pack.pptx"
)